-- FCTH CMS Database Schema

CREATE TABLE IF NOT EXISTS admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nome VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  etapa VARCHAR(50) NOT NULL,
  nome VARCHAR(200) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  local_nome VARCHAR(200) NOT NULL,
  data_display VARCHAR(100) NOT NULL,
  data_fim VARCHAR(20) NOT NULL,
  horario VARCHAR(100) DEFAULT 'A definir',
  garantido VARCHAR(100) DEFAULT NULL,
  banner_path VARCHAR(500) DEFAULT NULL,
  descricao TEXT,
  ordem INT DEFAULT 0,
  ativo TINYINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS partners (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(200) NOT NULL,
  logo_path VARCHAR(500) NOT NULL,
  dark_background TINYINT DEFAULT 0,
  ordem INT DEFAULT 0,
  ativo TINYINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS page_content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content_key VARCHAR(100) NOT NULL UNIQUE,
  content_value TEXT,
  content_type VARCHAR(50) DEFAULT 'text',
  page VARCHAR(50) NOT NULL,
  description VARCHAR(300) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS newsletter_signups (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(200) NOT NULL,
  email VARCHAR(300) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value TEXT
);

CREATE TABLE IF NOT EXISTS ranking_categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(200) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE,
  ordem INT DEFAULT 0,
  ativo TINYINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ranking_etapas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category_id INT NOT NULL,
  nome VARCHAR(100) NOT NULL,
  ordem INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES ranking_categories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ranking_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  etapa_id INT NOT NULL,
  posicao INT NOT NULL,
  nome VARCHAR(200) NOT NULL,
  pontos REAL NOT NULL DEFAULT 0,
  FOREIGN KEY (etapa_id) REFERENCES ranking_etapas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS gallery_photos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  src VARCHAR(500) NOT NULL,
  alt VARCHAR(300) DEFAULT '',
  etapa VARCHAR(50) NOT NULL,
  ordem INT DEFAULT 0,
  ativo TINYINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS uploaded_files (
  id INT AUTO_INCREMENT PRIMARY KEY,
  original_name VARCHAR(300) NOT NULL,
  stored_name VARCHAR(300) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  file_size INT DEFAULT 0,
  category VARCHAR(50) DEFAULT 'general',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
